server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin1234
    url: jdbc:mysql://127.0.0.1:3306/rdschool
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
